# Generated by Django 3.2.16 on 2023-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('imagem_url', models.URLField(verbose_name='URL da Imagem de Perfil')),
                ('descricao', models.TextField(max_length=4097, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
    ]
