# Generated by Django 3.2.16 on 2023-01-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
