# Generated by Django 3.2.16 on 2022-12-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20221210_1138'),
        ('professores', '0003_auto_20221210_1138'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
