# Generated by Django 3.2.16 on 2022-12-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='empresa_vinculada',
        ),
        migrations.AddField(
            model_name='aluno',
            name='empresa_vinculada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
            preserve_default=False,
        ),
    ]
