# Generated by Django 3.2.16 on 2022-12-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_aluno_empresa_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='descricao',
            field=models.TextField(blank=True, max_length=4097),
        ),
    ]
