# Generated by Django 3.2.16 on 2023-01-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_professor_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['usuario_aluno__first_name', 'usuario_aluno__last_name']},
        ),
    ]
