# Generated by Django 3.2.16 on 2023-01-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_aluno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='eh_aluno',
            field=models.BooleanField(default=False, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='eh_empresa',
            field=models.BooleanField(default=False, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='eh_professor',
            field=models.BooleanField(default=False, verbose_name='Professor'),
        ),
    ]
