# Generated by Django 3.2.16 on 2023-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20230119_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=30, verbose_name='Endereço'),
        ),
    ]
