# Generated by Django 3.2.16 on 2022-12-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('presentes', models.ManyToManyField(blank=True, null=True, to='alunos.Aluno')),
            ],
        ),
    ]
