# Generated by Django 3.2.16 on 2022-12-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20221210_1138'),
        ('professores', '0002_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='presentes',
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adm.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
