# Generated by Django 3.2.16 on 2022-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_auto_20221210_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
