# Generated by Django 3.2.16 on 2022-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0004_alter_aula_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='titulo',
            field=models.CharField(default='Sem Título', max_length=255),
        ),
    ]
