# Generated by Django 3.2.16 on 2022-12-15 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0005_aula_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 53, 56, 151637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo',
            field=models.CharField(default='Título da Aula', max_length=255),
        ),
    ]
