# Generated by Django 3.2.16 on 2022-12-15 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0006_auto_20221215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 55, 23, 427959, tzinfo=utc)),
        ),
    ]
