# Generated by Django 3.2.16 on 2022-12-15 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0007_alter_aula_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
