# Generated by Django 3.2.16 on 2022-12-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_aluno_empresa_professor'),
        ('professores', '0008_alter_aula_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.professor'),
        ),
    ]
