# Generated by Django 3.2.16 on 2022-12-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('alunos_do_curso', models.ManyToManyField(to='alunos.Aluno')),
                ('idioma_do_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.idioma')),
                ('professor_do_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professores.professor')),
            ],
        ),
    ]
