# Generated by Django 3.2.16 on 2022-12-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idioma',
            old_name='nome',
            new_name='idioma',
        ),
        migrations.AddField(
            model_name='curso',
            name='curso',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
