# Generated by Django 3.2.16 on 2022-12-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20221208_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(default='', max_length=30),
        ),
    ]
