# Generated by Django 3.2.16 on 2022-12-10 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_alter_curso_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pago', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.curso')),
            ],
        ),
    ]
