# Generated by Django 3.2.16 on 2022-12-10 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
