# Generated by Django 3.2.16 on 2022-12-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_aluno_empresa_professor'),
        ('adm', '0005_pagamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alunos_do_curso',
            field=models.ManyToManyField(to='usuarios.Aluno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='professor_do_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.professor'),
        ),
    ]
