# Generated by Django 3.2.16 on 2023-01-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_alter_curso_alunos_do_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aulas_pagas',
            field=models.IntegerField(default=0),
        ),
    ]
