# Generated by Django 3.2.16 on 2023-01-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_remove_curso_aulas_pagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aulas_pagas',
            field=models.IntegerField(default=0),
        ),
    ]
