# Generated by Django 3.2.16 on 2022-12-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_delete_aluno'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
